service: CRUD-dynamodb-lambda-serverless

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment: ${file(env.yml):${self:provider.stage}}
  memorySize: 128
  timeout: 10

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true


functions:
  read:
    handler: handler.read
    events:
      - http:
          method: get
          path: read
          cors: true
